fix: remove duplicate sentences
apitable/apitable pull request #271
Opened 2023-01-31 07:31 UTC by lingxyz

Submit a pull request for this project.

# Why? 

# What?

# How?

2023-01-31 07:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/apitable/apitable?pullRequest=271) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/apitable/apitable?pullRequest=271) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/apitable/apitable?pullRequest=271) it.</sub>

2023-02-13 15:57 UTC, mr-kelly commented
@lingxyz  Sorry, we have "rebased" the repository to eliminate duplicate, mistaken, and orphan commits and branches.

We cannot recognize what changes you have made...

Would you please re-fork (delete the forked repo and fork again) and make the real changes again?

2023-02-13 15:57 UTC, mr-kelly requested changes
@lingxyz  Sorry, we have "rebased" the repository to eliminate duplicate, mistaken, and orphan commits and branches.

We cannot recognize what changes you have made...

Would you please re-fork (delete the forked repo and fork again) and make the real changes again?

2023-04-10 01:24 UTC, closed without merging

2023-04-10 01:28 UTC, arucil commented
This problem has been fixed in other PR so we close this one.