fix: add aliyun oss file upload and download see the #174 issue for detail…
apitable/apitable pull request #279
Opened 2023-02-01 04:21 UTC by zhaoziyangcode

Added Alibaba Cloud OSS file upload and download

2023-02-01 04:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/apitable/apitable?pullRequest=279) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/apitable/apitable?pullRequest=279) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/apitable/apitable?pullRequest=279) it.</sub>

2023-02-02 16:39 UTC, shawndenggh commented on backend-server/application/src/main/resources/application.yml
> +cos:
why write these?

2023-02-13 16:01 UTC, mr-kelly requested changes
@zhaoziyangcode  Sorry, we have "rebased" the repository to eliminate duplicate, mistaken, and orphan commits and branches.

We cannot recognize what changes you have made...

Would you please re-fork (delete the forked repo and fork again) and make the real changes again?

Thanks for you contribution.

2023-04-16 14:49 UTC, hailin0 commented
I see doing a lot of things unrelated to the topic

2023-09-04 14:15 UTC, closed without merging