New Crowdin updates
apitable/apitable pull request #285
Opened 2023-02-01 10:47 UTC by mr-kelly

2023-03-27 09:16 UTC, Exclamation-mark reviewed
Only the files with the md suffix have been changed.
The translation results of some languages are not accurate enough and will be optimized later.

2023-03-27 09:18 UTC, Exclamation-mark approved these changes
approve

2023-03-27 09:26 UTC, yort-feng requested changes
There is no reason to use force-push, should revert the force-push commit

2023-03-28 08:31 UTC, Exclamation-mark commented on docs/readme/ar-SA/README.md
> -تعلم كيفية إعداد بيئتك المحلية، في [دليل المطور](./docs/contribute/developer-guide.md) لدينا.
这个地方Crowdin还没有推过来

2023-03-28 08:51 UTC, mr-kelly commented
Please update from https://github.com/apitable/apitable/pull/652  content

2023-03-28 09:58 UTC, yort-feng approved these changes

2023-03-28 11:23 UTC, merged